[package]
name = "aurorawidgets-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }

iced_futures = "0.13.2"
pulse = { package = "libpulse-binding", version = "2.28.2" }
flume = "0.11.1"
chrono = "0.4.40"

